# MacOS is used as our main CI environment for Flutter
macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3
container:
    image: cirrusci/flutter:latest

# ==== All tasks for shady_ai_flutter ====
shady_ai_flutter_task:
  env:
    CIRRUS_WORKING_DIR: "shady_ai_flutter/"
  pub_cache:
    folder: $HOME/.pub-cache
  script:
    - cd $CIRRUS_WORKING_DIR
    - flutter test
    - flutter analyze
    - flutter pub run dart_code_metrics:metrics check-unused-files lib --exclude="{/**.g.dart,/**.freezed.dart}"
    - flutter pub run dart_code_metrics:metrics check-unused-code lib --exclude="{/**.g.dart,/**.freezed.dart}"
    - dart format lib test --set-exit-if-changed
