analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # For example, this should throw an error: if (CarBrands.Tesla == 'Tesla') ...
    # Types must be explicitly enforced. This is just a personal preference of mine to avoid hardcoded strings.
    unrelated_type_equality_checks: error
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"

linter:
  rules:
    require_trailing_commas: true
    directives_ordering: true
    prefer_relative_imports: true
    always_use_package_imports: false

    # This rule is considered as experimental (2+ years already!)
    use_build_context_synchronously: false
