name: shady_ai
description: Making offline AI models accessible to all types of edge devices.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Required to enable localization
    sdk: flutter         # Required to enable localization
  serverpod_flutter: ^1.1.1
  shady_ai_client:
    path: ../shady_ai_client
  slick_slides:
    git:
      url: https://github.com/BrutalCoding/slick_slides.git
      ref: main
      path: slick_slides
  cupertino_icons: ^1.0.6
  ffi: ^2.1.0
  hooks_riverpod: ^2.4.0
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0
  go_router: ^13.0.1
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  desktop_drop: ^0.4.3
  super_hot_key: ^0.7.0
  window_manager: ^0.3.6
  collection: ^1.17.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  #
  # Experimental. I was able to compile "flutter build web --wasm" but only without serverpod_flutter.
  # serverpod_flutter relies on a connectivity package, which uses dart:html.
  # dart:html is causing troubles together with the --wasm flag.
  # If you want to try it out, make sure you're on the latest flutter master channel.
  # For more info, visit: https://github.com/dart-lang/wasm/tree/main/flutter_wasm
  #
  # flutter_wasm:
  #   git:
  #     url: https://github.com/dart-lang/wasm.git
  #     path: flutter_wasm

dev_dependencies:
  flutter_test:
      sdk: flutter
  build_runner: ^2.4.6
  ffigen: ^9.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1 # Contains a set of recommended lints for Flutter code
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.2

# Generates bindings for llama.cpp
ffigen:
  name: LLaMa
  description: llama.cpp bindings
  output: 'lib/generated/llama.cpp/llama.cpp_bindings.g.dart'
  comments:
    style: any
    length: full
  headers:
    entry-points:
      # - '/example/absolute/path/to/llama.cpp/llama.h'
      - /Users/brutalcoding/Development/Repos/llama.cpp/llama.h
  preamble: |
    // ignore_for_file: deprecated_member_use

# # Generates bindings for rwkv.cpp
# ffigen:
#   name: RWKV
#   description: rwkv.cpp bindings
#   output: 'lib/generated/rwkv.cpp/rwkv.cpp_bindings.g.dart'
#   headers:
#     entry-points:
#       - '# - /example/absolute/path/to/rwkv.cpp/rwkv.h'
#   preamble: |
#     // ignore_for_file: deprecated_member_use

# Launcher icons generator plugin
#
# To generate icons, enter this in the terminal:
# > flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dad_the_benchmark_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
  web:
    generate: true
  windows:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dad_the_benchmark.png
    - assets/dylibs/
