name: shady_ai_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod: 1.0.1

dev_dependencies:
  lints: ^2.0.0
  dart_code_metrics: ^5.7.2
  test: ^1.24.1
